cmake_minimum_required(VERSION 3.22)

include_guard(GLOBAL)

include(BluespecUtils)

# Function: add_bluesim_systemc_library
#   Add a library for the Bluesim SystemC model generated by Bluespec.
#
# Usage:
#   add_bluesim_systemc_library(<TARGET> <TOP_MODULE> <ROOT_SOURCE> [source_files...]
#                               [BSC_FLAGS <flags...>]
#                               [LINK_LIBS <libs...>] [LINK_C_LIBS <libs...>]
#                               [C_FLAGS <flags...>] [CXX_FLAGS <flags...>]
#                               [CPP_FLAGS <flags...>] [LD_FLAGS <flags...>])
#
# Arguments:
#   TARGET       - The target name.
#   TOP_MODULE   - Top module to generate the Bluesim executable.
#   ROOT_SOURCE  - Source to the root compilation unit.
#   source_files - Additional source files/directories to include in search path.
#
# Options:
#   BSC_FLAGS   - Multiple flags to be appended during compilation.
#   LINK_LIBS   - List of Bluespec library targets to link against.
#   LINK_C_LIBS - List of foreign C library targets to link against.
#   C_FLAGS     - Arguments passed to the C compiler.
#   CXX_FLAGS   - Arguments passed to the C++ compiler.
#   CPP_FLAGS   - Arguments passed to the C preprocessor.
#   LD_FLAGS    - Arguments passed to the C/C++ linker.
#
# Generates:
#   A target named <TARGET> and a Bluesim SystemC target Bluesim.SystemC.lib<TARGET>
function(add_bluesim_systemc_library TARGET TOP_MODULE ROOT_SOURCE)
  set(_options)
  set(_one_args)
  set(_multi_args
    BSC_FLAGS    LINK_LIBS     LINK_C_LIBS
    C_FLAGS      CXX_FLAGS     CPP_FLAGS    LD_FLAGS
  )

  cmake_parse_arguments(ARG "${_options}" "${_one_args}" "${_multi_args}" ${ARGN})

  # 1. Handle absolute paths and extract directories
  get_filename_component(_abs_root_source "${ROOT_SOURCE}" ABSOLUTE)
  
  set(_all_sources "${_abs_root_source}")
  set(_src_dirs "")

  # Extract directories from the remaining sources
  foreach(_src ${ARG_UNPARSED_ARGUMENTS})
    get_filename_component(_abs_path "${_src}" ABSOLUTE)
    list(APPEND _all_sources "${_abs_path}")
    get_filename_component(_dir_path "${_abs_path}" DIRECTORY)
    list(APPEND _src_dirs "${_dir_path}")
  endforeach()

  list(REMOVE_DUPLICATES _all_sources)
  list(REMOVE_DUPLICATES _src_dirs)

  # 2. Set Target name and path
  set(_bsim_sc_target "Bluesim.SystemC.lib${TARGET}")
  set(_sim_dir "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/${_bsim_sc_target}.dir")

  if(CMAKE_LIBRARY_OUTPUT_DIRECTORY)
    set(_target_lib_dir "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
  elseif(CMAKE_ARCHIVE_OUTPUT_DIRECTORY)
    set(_target_lib_dir "${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
  else()
    set(_target_lib_dir "${_sim_dir}")
  endif()

  set(_target_lib "${_target_lib_dir}/lib${TARGET}.a")
  add_custom_target(${_bsim_sc_target} ALL DEPENDS "${_target_lib}")

  if(ARG_LINK_LIBS)
    add_dependencies(${_bsim_sc_target} ${ARG_LINK_LIBS})
  endif()

  set(_bdir "${_sim_dir}/${TOP_MODULE}.dir")
  file(MAKE_DIRECTORY "${_bdir}")

  # 3. Prepare BSC compilation flags
  set(_bsim_sc_flags ${ARG_BSC_FLAGS})
  bsc_setup_path_flags(_bsim_sc_flags
    BDIR      "${_bdir}"
    INFO_DIR  "${_bdir}"
    SIMDIR    "${_sim_dir}"
    SRC_DIRS  ${_src_dirs}
    LINK_LIBS ${ARG_LINK_LIBS}
  )

  bsc_setup_sim_flags(_bsim_sc_flags)
  set(_bsc_cmd ${BSC_BIN} ${_bsim_sc_flags})

  # 4. Calculate Hash and execute Pre-elaboration (with caching)
  string(MD5 _hash "${_abs_root_source};${TOP_MODULE};${ARGN}")

  bsc_pre_elaboration(
    _blue_objects ${_hash} ${_all_sources}
    BSC_FLAGS ${_bsim_sc_flags}
  )

  # 5. Elaborate Bluespec module
  set(_elab_module "${_bdir}/${TOP_MODULE}.ba")
  file(RELATIVE_PATH _elab_module_path "${CMAKE_BINARY_DIR}" "${_elab_module}")

  add_custom_command(
    OUTPUT  "${_elab_module}"
    COMMAND ${_bsc_cmd} "-g" ${TOP_MODULE} "${_abs_root_source}"
    COMMAND ${CMAKE_COMMAND} -E touch "${_elab_module}"
    DEPENDS ${_blue_objects}
    COMMENT "Elaborating Bluespec module ${_elab_module_path}"
    VERBATIM
  )

  # 6. Generate SystemC Model
  bsc_get_bluesim_targets(_bsim_targets ${TOP_MODULE} SIMDIR "${_sim_dir}")
  bsc_get_bluesim_sc_targets(_bsim_sc_targets ${TOP_MODULE} SIMDIR "${_sim_dir}")
  bsc_get_parallel_sim_link_jobs(_jobs)
  bsc_get_link_c_lib_files(_link_c_lib_files LINK_C_LIBS ${ARG_LINK_C_LIBS})
  bsc_setup_systemc_include_flags(_systemc_inc)
  
  bsc_setup_c_cxx_flags(_c_cxx_flags
    C_FLAGS   ${ARG_C_FLAGS}
    CXX_FLAGS ${ARG_CXX_FLAGS}
    CPP_FLAGS ${ARG_CPP_FLAGS}
    LD_FLAGS  ${ARG_LD_FLAGS}
  )

  add_custom_command(
    OUTPUT  ${_bsim_targets} ${_bsim_sc_targets}
    COMMAND ${_bsc_cmd} ${_c_cxx_flags} "-systemc" "-parallel-sim-link" ${_jobs}
            "-e" ${TOP_MODULE} ${_systemc_inc} ${_link_c_lib_files}
    DEPENDS "${_elab_module}" ${ARG_LINK_C_LIBS}
    COMMENT "Generating SystemC model for ${TOP_MODULE}"
    VERBATIM
  )

  # 7. Package generated object files into a static library (.a)
  file(RELATIVE_PATH _target_lib_path "${CMAKE_BINARY_DIR}" "${_target_lib}")
  
  # Note: Be careful when using shell wildcard (*.o) in add_custom_command
  # Keeping your logic here, but suggest ensuring WORKING_DIRECTORY is correct
  add_custom_command(
    OUTPUT  "${_target_lib}"
    COMMAND "${CMAKE_AR}" "rcs" "${_target_lib}" *.o
    WORKING_DIRECTORY "${_sim_dir}"
    DEPENDS ${_bsim_targets} ${_bsim_sc_targets}
    COMMENT "Linking Bluesim SystemC library ${_target_lib_path}"
  )

  # 8. Create IMPORTED Target for external linking
  if(NOT TARGET ${TARGET})
    add_library(${TARGET} INTERFACE IMPORTED GLOBAL)
    add_dependencies(${TARGET} ${_bsim_sc_target})
    set_target_properties(${TARGET}
      PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${_sim_dir}"
        INTERFACE_LINK_LIBRARIES "${_target_lib}"
    )
    target_link_libraries(${TARGET} INTERFACE BSC::bskernel BSC::bsprim)
  endif()
endfunction()
